# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 300 # Hz
    cycle_time_error_threshold: 0.03

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    body_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    head_imu_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

    l_arm_fts_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    r_arm_fts_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster
    
    wheels_controller:
      type: diff_drive_controller/DiffDriveController

l_arm_fts_broadcaster:
  ros__parameters:
    interface_names.force.x: l_arm_fts/force.x
    interface_names.force.y: l_arm_fts/force.y
    interface_names.force.z: l_arm_fts/force.z
    interface_names.torque.x: l_arm_fts/torque.x
    interface_names.torque.y: l_arm_fts/torque.y
    interface_names.torque.z: l_arm_fts/torque.z
    frame_id: l_arm_force_sensor_link

r_arm_fts_broadcaster:
  ros__parameters:
    interface_names.force.x: r_arm_fts/force.x
    interface_names.force.y: r_arm_fts/force.y
    interface_names.force.z: r_arm_fts/force.z
    interface_names.torque.x: r_arm_fts/torque.x
    interface_names.torque.y: r_arm_fts/torque.y
    interface_names.torque.z: r_arm_fts/torque.z
    frame_id: r_arm_force_sensor_link

head_imu_broadcaster:
  ros__parameters:
    frame_id: head_imu_frame
    sensor_name: head_imu
    static_covariance_orientation: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    static_covariance_angular_velocity:
      [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    static_covariance_linear_acceleration:
      [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

body_controller:
  ros__parameters:
    joints:
      - ankle_p_joint
      - knee_p_joint
      - waist1_p_joint
      - waist2_y_joint
      - head1_y_joint
      - head2_p_joint
      - l_arm1_shoulder_p_joint
      - l_arm2_shoulder_r_joint
      - l_arm3_shoulder_y_joint
      - l_arm4_elbow_p_joint
      - l_arm5_wrist_y_joint
      - l_arm6_wrist_p_joint
      - l_arm7_wrist_r_joint
      - r_arm1_shoulder_p_joint
      - r_arm2_shoulder_r_joint
      - r_arm3_shoulder_y_joint
      - r_arm4_elbow_p_joint
      - r_arm5_wrist_y_joint
      - r_arm6_wrist_p_joint
      - r_arm7_wrist_r_joint
      - l_thumb_cmc_y_joint
      - l_thumb_cmc_p_joint
      - l_index_mcp_joint
      - l_middle_mcp_joint
      - l_ring_mcp_joint
      - l_pinky_mcp_joint
      - r_thumb_cmc_y_joint
      - r_thumb_cmc_p_joint
      - r_index_mcp_joint
      - r_middle_mcp_joint
      - r_ring_mcp_joint
      - r_pinky_mcp_joint
    command_interfaces:
      - position
      # - effort
    state_interfaces:
      - position
      - velocity
    open_loop_control: true
    allow_partial_joints_goal: true


wheels_controller:
  ros__parameters:
    left_wheel_names: ["lf_wheel_joint", "lb_wheel_joint"]
    right_wheel_names: ["rf_wheel_joint", "rb_wheel_joint"]

    wheel_separation: 0.46
    wheel_radius: 0.101

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    odom_frame_id: odom
    base_frame_id: base_footprint
    pose_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    twist_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    position_feedback: true
    open_loop: false
    enable_odom_tf: true
    use_stamped_vel: false

    cmd_vel_timeout: 0.5 # seconds
    publish_limited_velocity: true
    velocity_rolling_window_size: 10

    linear.x.max_velocity: .NAN
    linear.x.min_velocity: .NAN
    linear.x.max_acceleration: .NAN
    linear.x.max_deceleration: .NAN
    linear.x.max_acceleration_reverse: .NAN
    linear.x.max_deceleration_reverse: .NAN
    linear.x.max_jerk: .NAN
    linear.x.min_jerk: .NAN

    angular.z.max_velocity: .NAN
    angular.z.min_velocity: .NAN
    angular.z.max_acceleration: .NAN
    angular.z.max_deceleration: .NAN
    angular.z.max_acceleration_reverse: .NAN
    angular.z.max_deceleration_reverse: .NAN
    angular.z.max_jerk: .NAN
    angular.z.min_jerk: .NAN