#### camera ####
head_front_left_fisheye_color:
  update_rate: 60
  horizontal_fov: 2.26893
  image_width: 1280
  image_height: 800
  image_format: "R8G8B8"
  clip_near: 0.05
  clip_far: 300

head_front_right_fisheye_color:
  update_rate: 60
  horizontal_fov: 2.26893
  image_width: 1280
  image_height: 800
  image_format: "R8G8B8"
  clip_near: 0.05
  clip_far: 300

head_left_fisheye_color:
  update_rate: 60
  horizontal_fov: 2.26893
  image_width: 1280
  image_height: 800
  image_format: "R8G8B8"
  clip_near: 0.05
  clip_far: 300

head_right_fisheye_color:
  update_rate: 60
  horizontal_fov: 2.26893
  image_width: 1280
  image_height: 800
  image_format: "R8G8B8"
  clip_near: 0.05
  clip_far: 300

head_camera_color:
  update_rate: 60
  horizontal_fov: 1.211259
  image_width: 1920
  image_height: 1080
  image_format: "R8G8B8"
  clip_near: 0.1
  clip_far: 300

head_camera_infra1:
  update_rate: 60
  horizontal_fov: 1.59174
  image_width: 1280
  image_height: 800
  image_format: "R8G8B8"
  clip_near: 0.1
  clip_far: 300

head_camera_infra2:
  update_rate: 60
  horizontal_fov: 1.59174
  image_width: 1280
  image_height: 800
  image_format: "R8G8B8"
  clip_near: 0.1
  clip_far: 300

head_camera_depth:
  update_rate: 60
  horizontal_fov: 1.51843
  image_width: 1280
  image_height: 720
  image_format: "R8G8B8"
  clip_near: 0.1
  clip_far: 300

trunk_camera_color:
  update_rate: 60
  horizontal_fov: 1.211259
  image_width: 1920
  image_height: 1080
  image_format: "R8G8B8"
  clip_near: 0.05
  clip_far: 300

trunk_camera_infra1:
  update_rate: 60
  horizontal_fov: 1.59174
  image_width: 1280
  image_height: 800
  image_format: "R8G8B8"
  clip_near: 0.1
  clip_far: 300

trunk_camera_infra2:
  update_rate: 60
  horizontal_fov: 1.59174
  image_width: 1280
  image_height: 800
  image_format: "R8G8B8"
  clip_near: 0.1
  clip_far: 300

trunk_camera_depth:
  update_rate: 60
  horizontal_fov: 1.51843
  image_width: 1280
  image_height: 720
  image_format: "R8G8B8"
  clip_near: 0.1
  clip_far: 300

l_wrist_camera1_color:
  update_rate: 60
  horizontal_fov: 1.74358
  image_width: 1600
  image_height: 1200
  image_format: "R8G8B8"
  clip_near: 0.05
  clip_far: 300

l_wrist_camera2_color:
  update_rate: 60
  horizontal_fov: 1.74358
  image_width: 1600
  image_height: 1200
  image_format: "R8G8B8"
  clip_near: 0.05
  clip_far: 300

r_wrist_camera1_color:
  update_rate: 60
  horizontal_fov: 1.74358
  image_width: 1600
  image_height: 1200
  image_format: "R8G8B8"
  clip_near: 0.05
  clip_far: 300

r_wrist_camera2_color:
  update_rate: 60
  horizontal_fov: 1.74358
  image_width: 1600
  image_height: 1200
  image_format: "R8G8B8"
  clip_near: 0.05
  clip_far: 300